FROM maven:3.9.6-eclipse-temurin-22-jammy AS build
COPY server ./server
COPY .vscode ./vscode
RUN mvn clean package -DskipTests

FROM gradle:jdk-21-and-22-jammy
COPY --from=build /server/target/server-0.0.1-SNAPSHOT.jar server.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","server.jar" ]